backend:
  name: git-gateway
  branch: master  # Cambia "master" a "main" (rama por defecto actual en GitHub)

media_folder: "img/galeria"  
public_folder: "/img/galeria"  

# Añade esto para mejor manejo de imágenes
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: "galeria"
    label: "Galería"
    files:
      - name: "data"  # Nombre interno (sin tildes)
        label: "Imágenes del Carrusel"
        file: "img/galeria/data.json"
        fields:
          - name: "imagenes"
            label: "Imágenes"
            widget: "list"
            summary: "{{fields.titulo}}"
            fields:
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Imagen", name: "src", widget: "image" }