backend:
  name: git-gateway
  branch: master

media_folder: "img/galeria"  # Carpeta donde se guardarán las imágenes
public_folder: "/img/galeria"  # Ruta pública

collections:
  - name: "galeria"
    label: "Galería"
    files:
      - name: "galeria"
        label: "Imágenes del Carrusel"
        file: "data/galeria.json"  # Archivo JSON que generará Netlify CMS
        fields:
          - { name: "imagenes", label: "Imágenes", widget: "list", 
              fields: [
                { label: "Imagen", name: "src", widget: "image" },
                { label: "Título", name: "titulo", widget: "string" }
              ] }