backend:
  name: github
  repo: Moisecx/portfolio  # Reemplázalo con tu usuario y repositorio de GitHub
  branch: master  # O "main", dependiendo de tu rama principal

media_folder: "img"  # Carpeta donde se guardarán las imágenes
public_folder: "/img"  # Ruta pública de las imágenes

collections:
  - name: "galeria"
    label: "Galería"
    folder: "galeria"  # Nombre de la carpeta que se utilizará para almacenar los archivos
    create: true  # Habilita la opción para crear nuevas imágenes
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
