backend:
  name: netlify
  branch: master  # O la rama principal de tu repositorio (puede ser "main")

media_folder: "img"  # Carpeta donde se guardarán las imágenes
public_folder: "/img"  # Ruta pública de las imágenes

collections:
  - name: "galeria"
    label: "Galería"
    folder: "galeria"  # Nombre de la carpeta que se utilizará para almacenar los archivos
    create: true  # Habilita la opción para crear nuevas imágenes
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
